---
#
#------------------------------------------------------------------------------
# Description: Install NRPE on selected hosts
#
#-------------------------------------------------------------------------------

#- name: pull nagios installation zip file from Ansible server to remote host
#  copy:
#    scr: /home/ansible/DA-Ansible/files/linux-nrpe-agent.tar.gz
#    dest: /tmp
#    owner: root
#    group: root
#    mode: '0644'

#- name: remove the working folder if exists, uncomment it when you need to reinstall the NRPE
#  file:
#    state: absent
#    path: /tmp/linux-nrpe-agent

- name: Extract nagios installation zip file
  unarchive:
    src: /home/ansible/DA-Ansible/files/linux-nrpe-agent.tar.gz
    dest: /tmp
  #remote_src: yes
    remote_src: no

- name: Install and Compile NRPE and Nagios plugins
  shell: ./fullinstall -n -i 192.168.3.125 >> "nrpe_{{ ansible_hostname }}.log"
  args:
    executable: /bin/bash
    creates: "nrpe_{{ ansible_hostname }}.log"
    chdir: /tmp/linux-nrpe-agent

- name: Check the nrpe status from Nagios server
  command: /usr/lib64/nagios/plugins/check_nrpe -H {{ ansible_default_ipv4.address }}
  register: nrpe_version
  delegate_to: 192.168.3.125

- name: Show the NRPE version
  debug:
    msg: Server {{ ansible_hostname }} IP {{ ansible_default_ipv4.address }}  has installed {{ nrpe_version.stdout }}



